'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OGBatteryMod.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Battery1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Battery2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property BatteryMod() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryMod", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;item type=&quot;id&quot; name=&quot;OG_Battery_LL1&quot;&gt;false&lt;/item&gt;
        '''    &lt;item type=&quot;id&quot; name=&quot;OG_Battery_LL2&quot;&gt;false&lt;/item&gt;
        '''    &lt;item type=&quot;id&quot; name=&quot;OG_Battery_Name&quot;&gt;false&lt;/item&gt;
        '''    &lt;item type=&quot;id&quot; name=&quot;OG_Battery_CBox&quot;&gt;false&lt;/item&gt;
        '''    &lt;item type=&quot;id&quot; name=&quot;OG_Battery_Icon1&quot;&gt;false&lt;/item&gt;
        '''    &lt;item type=&quot;id&quot; name=&quot;OG_Battery_Icon2&quot;&gt;false&lt;/item&gt;
        '''    &lt;item type=&quot;id&quot; name=&quot;OG_Battery_Icon3&quot;&gt;false&lt;/item&gt;
        '''    &lt;item type=&quot;id&quot; name=&quot;OG_Battery_Icon4&quot;&gt;false&lt;/item&gt;
        '''    &lt;item type=&quot;id&quot; name=&quot;OG_Battery_Icon5&quot;&gt;false&lt;/item&gt;.
        '''</summary>
        Friend ReadOnly Property IDs() As String
            Get
                Return ResourceManager.GetString("IDs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OGBatteryMod() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OGBatteryMod", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;com.ghareeb.BatteryMod.BatteryList android:entries=&quot;@array/BatteryStyles&quot; android:title=&quot;@string/battry_style_title&quot; android:key=&quot;batterystyle&quot; android:summary=&quot;@string/battry_style_summary&quot; android:defaultValue=&quot;Default&quot; android:entryValues=&quot;@array/BatteryStyles&quot; /&gt;.
        '''</summary>
        Friend ReadOnly Property SettingsXML() As String
            Get
                Return ResourceManager.GetString("SettingsXML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;string-array name=&quot;BatteryStyles&quot;&gt;
        '''        &lt;item&gt;Default&lt;/item&gt;
        '''        &lt;item&gt;Aeon&lt;/item&gt;
        '''        &lt;item&gt;Android&lt;/item&gt;
        '''        &lt;item&gt;Broken Circle&lt;/item&gt;
        '''        &lt;item&gt;Bubble&lt;/item&gt;
        '''        &lt;item&gt;C&lt;/item&gt;
        '''        &lt;item&gt;Chrysis&lt;/item&gt;
        '''        &lt;item&gt;Circle&lt;/item&gt;
        '''        &lt;item&gt;Froyo&lt;/item&gt;
        '''        &lt;item&gt;Grey Tiny Circle&lt;/item&gt;
        '''        &lt;item&gt;ICS Sphere&lt;/item&gt;
        '''        &lt;item&gt;iPhone&lt;/item&gt;
        '''        &lt;item&gt;Numas&lt;/item&gt;
        '''        &lt;item&gt;Sense&lt;/item&gt;
        '''        &lt;item&gt;Vertical ICS Blue&lt;/item&gt;
        '''    &lt;/string-ar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Styles() As String
            Get
                Return ResourceManager.GetString("Styles", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
