'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OGBatteryMod.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .method public addIcon(Ljava/lang/String;IILcom/android/internal/statusbar/StatusBarIcon;)V
        '''    .locals 5
        '''    .parameter &quot;slot&quot;
        '''    .parameter &quot;index&quot;
        '''    .parameter &quot;viewIndex&quot;
        '''    .parameter &quot;icon&quot;
        '''
        '''    .prologue
        '''    .line 24
        '''    new-instance v0, Lcom/android/systemui/statusbar/StatusBarIconView;
        '''
        '''    invoke-direct {v0, p0, p1}, Lcom/android/systemui/statusbar/StatusBarIconView;-&gt;&lt;init&gt;(Landroid/content/Context;Ljava/lang/String;)V
        '''
        '''    .line 25
        '''    .local v0, view:Lcom/android/systemui/stat [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property addIcon() As String
            Get
                Return ResourceManager.GetString("addIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ui_print(&quot;===================================&quot;);
        '''ui_print(&quot;* OGBatteryMod By &lt;Osama Ghareeb&gt; *&quot;);
        '''ui_print(&quot;===================================&quot;);
        '''show_progress(1.000000, 0);
        '''package_extract_file(&quot;system/xbin/busybox&quot;, &quot;/tmp/busybox&quot;);
        '''set_perm(0, 0, 0777, &quot;/tmp/busybox&quot;);
        '''set_progress(0.200000);
        '''ui_print(&quot;Mounting system...&quot;);
        '''run_program(&quot;/tmp/busybox&quot;, &quot;mount&quot;, &quot;/system&quot;);
        '''set_progress(0.300000);
        '''ui_print(&quot;Removing old SystemUI&quot;);
        '''delete(&quot;/system/app/{0}&quot;);
        '''delete(&quot;/system/app/{1}&quot;);
        '''set_pro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BackupScript() As String
            Get
                Return ResourceManager.GetString("BackupScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Battery1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property BatteryMod() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryMod", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OGBatteryMod() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OGBatteryMod", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OGBatteryMod1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OGBatteryMod1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ui_print(&quot;===================================&quot;);
        '''ui_print(&quot;* OGBatteryMod By &lt;Osama Ghareeb&gt; *&quot;);
        '''ui_print(&quot;===================================&quot;);
        '''show_progress(1.000000, 0);
        '''package_extract_file(&quot;system/xbin/busybox&quot;, &quot;/tmp/busybox&quot;);
        '''set_perm(0, 0, 0777, &quot;/tmp/busybox&quot;);
        '''set_progress(0.200000);
        '''ui_print(&quot;Mounting system...&quot;);
        '''run_program(&quot;/tmp/busybox&quot;, &quot;mount&quot;, &quot;/system&quot;);
        '''set_progress(0.300000);
        '''ui_print(&quot;Removing old SystemUI&quot;);
        '''delete(&quot;/system/app/{0}&quot;);
        '''delete(&quot;/system/app/{1}&quot;);
        '''set_pro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Script() As String
            Get
                Return ResourceManager.GetString("Script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;PreferenceScreen android:summary=&quot;@string/battry_style_summary&quot; android:title=&quot;@string/battry_style_title&quot; &gt;
        '''        &lt;intent android:action=&quot;com.ghareeb.battery.Settings&quot;/&gt;
        '''&lt;/PreferenceScreen&gt;.
        '''</summary>
        Friend ReadOnly Property SettingsXML() As String
            Get
                Return ResourceManager.GetString("SettingsXML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;string-array name=&quot;BatteryStyles&quot;&gt;
        '''{0}
        '''&lt;/string-array&gt;.
        '''</summary>
        Friend ReadOnly Property Styles() As String
            Get
                Return ResourceManager.GetString("Styles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .method public updateIcon(Ljava/lang/String;IILcom/android/internal/statusbar/StatusBarIcon;Lcom/android/internal/statusbar/StatusBarIcon;)V
        '''    .locals 2
        '''    .parameter &quot;slot&quot;
        '''    .parameter &quot;index&quot;
        '''    .parameter &quot;viewIndex&quot;
        '''    .parameter &quot;old&quot;
        '''    .parameter &quot;icon&quot;
        '''
        '''    .prologue
        '''    .line 39
        '''    const-string v1, &quot;battery&quot;
        '''
        '''    invoke-virtual {p1, v1}, Ljava/lang/String;-&gt;equals(Ljava/lang/Object;)Z
        '''
        '''    move-result v1
        '''
        '''    if-nez v1, :cond_0
        '''
        '''    .line 40
        '''    iget-object v1, p0, Lcom [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property updateIcon() As String
            Get
                Return ResourceManager.GetString("updateIcon", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
